# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: github
    target: master
    tagSource: gitTag
    tagPattern: 'v.*'
    title: tantanatantan
    releaseNotesSource: inline
    changeLogType: issueBased
    changeLogCompareToRelease: lastNonDraftReleaseByTag
    changeLogCompareToReleaseTag: 'v.*'
    changeLogLabels: '[{"label": "trust", "displayName": "Trust Issues", "state": "open"}, {"label": "bug", "displayName": "Bugs Fixed", "state": "closed"}]'

- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: github
    target: efficiency
    tagSource: gitTag
    tagPattern: 'dev.*'
    title: tantanatantan
    releaseNotesSource: inline
    changeLogType: issueBased
    changeLogCompareToRelease: lastNonDraftReleaseByTag
    changeLogCompareToReleaseTag: 'dev.*'
    changeLogLabels: '[{"label": "trust", "displayName": "Trust Issues", "state": "open"}, {"label": "bug", "displayName": "Bugs Fixed", "state": "closed"}]'